// Built-in N2 study content — accurate patterns, kanji, vocab, readings, and Anki cards.
// Anki deck is loaded on demand from /data/ankiVocab.json (OpenJLPT, CC BY-SA 4.0).

export const scores = [
  { id: 'lang', name: 'Language Knowledge (Vocabulary/Grammar)', raw: '12 / 60', pct: 20, cutoff: '19 / 60', status: 'failed', target: '65% – 70%', color: 'rose' },
  { id: 'read', name: 'Reading Comprehension', raw: '16 / 60', pct: 27, cutoff: '19 / 60', status: 'failed', target: '65%', color: 'rose' },
  { id: 'listen', name: 'Listening Comprehension', raw: '36 / 60', pct: 60, cutoff: '19 / 60', status: 'passed', target: 'Maintain 60%', color: 'emerald' },
  { id: 'total', name: 'Total Aggregate', raw: '64 / 180', pct: 36, cutoff: '90 / 180', status: 'failed', target: '100+ for cushion', color: 'amber' },
]

export const plan = [
  { stage: 1, phase: 'Phase 1: Vocabulary Expansion & Core Kanji', focus: 'Build active recall for ~6,000 words and 1,000–1,250 kanji.', actions: [
    'Use an N2 SRS deck (20–25 new cards every morning).',
    'Decompose kanji by radicals and create vivid mental stories.',
    'Study collocations, not isolated words.',
    'Drill 5–10 kanji reading/context questions daily.',
    'Separate transitive/intransitive verb pairs explicitly.' ] },
  { stage: 1, phase: 'Phase 2: Grammar Mastery & Nuance Distinction', focus: 'Master ~180–211 N2 patterns with visual and contextual memory.', actions: [
    'Group grammar by meaning, not alphabetically.',
    'Attach each point to a visual scene (dual-coding).',
    'Write two original sentences for every new structure.',
    'Practice scrambled-sentence ordering from the back forward.',
    'Drill nuance differences between near-synonyms.' ] },
  { stage: 1, phase: 'Phase 3: Reading Speed & Conjunction Strategy', focus: 'Train parsing and time management on unedited native texts.', actions: [
    'Start with the question stem, then the passage.',
    'Anchor on the final predicate before the details.',
    'Bracket modifying clauses and map は/が/を/に.',
    'Circle structural conjunctions and contrast markers.',
    'Practice short (3 min), medium (9 min), and long (9 min) passages.' ] },
  { stage: 2, phase: 'Phase 4: Test Endurance & Mock Exams', focus: 'Build 105-minute literacy stamina and fine-tune pacing.', actions: [
    'Month 1: 30 min vocab + 60 min grammar + 60 min reading (6–10 h/week).',
    'Month 2 weeks 1–2: target weak points; weeks 3–4: full mock tests.',
    'Allocate exactly 30 min to Vocabulary/Grammar, 75 min to Reading.',
    'Take full weekend mocks under real conditions.',
    'Maintain and pre-review an error log.' ] },
]

export const readingTips = [
  { title: 'Clause Deconstruction', items: [
    'Anchor on the final predicate first.',
    'Bracket relative clauses as single adjective blocks.',
    'Map は, が, を, に to find who did what to whom.' ] },
  { title: 'Eye-Training Speed', items: [
    'Tracker-and-Pacer: guide eyes with a card to stop regressions.',
    'Phrase chunking: swallow 2–3 words or one pattern per glance.' ] },
  { title: 'Retention Loop', items: [
    'Pass 1: read for gist, no lookups.',
    'Pass 2: mine 5–10 items and add to SRS with full context.',
    'Pass 3: re-read at native speed to lock fluency.' ] },
]

export const resources = [
  { name: 'JLPT Sensei N2 Grammar', use: 'Categorized N2 grammar list with examples', category: 'Web', url: 'https://jlptsensei.com/jlpt-n2-grammar-list/' },
  { name: 'Imabi', use: 'Deep English-based grammar analysis', category: 'Web', url: 'https://imabi.net/' },
  { name: 'Maggie Sensei N2', use: 'Natural Japanese explanations and quizzes', category: 'Web', url: 'https://maggiesensei.com/' },
  { name: 'Tofugu Grammar', use: 'Articles on tricky Japanese grammar points', category: 'Web', url: 'https://www.tofugu.com/japanese-grammar/' },
  { name: 'Jisho', use: 'Free dictionary, kanji lookup, and radicals', category: 'Web', url: 'https://jisho.org/' },
  { name: 'Nihongo no Mori (N2)', use: 'Native teacher grammar & reading videos', category: 'Video', url: 'https://www.youtube.com/watch?v=sBXdW7NmwiQ', video: 'https://www.youtube-nocookie.com/embed/sBXdW7NmwiQ?modestbranding=1&rel=0&iv_load_policy=3' },
  { name: 'JLPT N2 Vocab Practice', use: 'N2 vocab usage with practice questions', category: 'Video', url: 'https://www.youtube.com/watch?v=WmIdm9GZQR4', video: 'https://www.youtube-nocookie.com/embed/WmIdm9GZQR4?modestbranding=1&rel=0&iv_load_policy=3' },
  { name: 'JLPT N2 Kanji List', use: 'Full N2 kanji list with vocabulary', category: 'Video', url: 'https://www.youtube.com/watch?v=tWIN1DEgU98', video: 'https://www.youtube-nocookie.com/embed/tWIN1DEgU98?modestbranding=1&rel=0&iv_load_policy=3' },
  { name: 'Japanese Ammo with Misa', use: 'Friendly grammar and JLPT strategy videos', category: 'Web', url: 'https://www.youtube.com/c/JapaneseAmmowithMisa' },
  { name: 'Nihongo Con Teppei', use: 'Daily N3-N2 listening podcasts for free', category: 'Web', url: 'https://www.youtube.com/@nihongoconteppei' },
  { name: 'NHK News Web Easy', use: 'Simplified Japanese news for reading warm-up', category: 'Reading', url: 'https://www3.nhk.or.jp/news/easy/' },
  { name: 'Todai Japanese', use: 'Daily native article reader with dictionary', category: 'Reading', url: 'https://www.todaii.com/' },
  { name: 'Official JLPT Sample Materials', use: 'Authentic practice sets from the test maker', category: 'Mock', url: 'https://www.jlpt.jp/e/samples/sampleindex.html' },
  { name: 'JLPT N2 Practice Questions', use: 'Free online past-style drills and mock tests', category: 'Mock', url: 'https://www.jlpt-n5-n1.com/jlpt-n2-practice-tests/' },
]

// Helper to create a small vocabulary row for example sentences.
const g = (word, reading, meaning) => ({ word, reading, meaning })

// ------------------------------------------------------------------
// KANJI LESSONS
// ------------------------------------------------------------------
export const kanjiLessons = [
  { char: '録', meaning: 'record', meaningFr: 'enregistrement', on: 'ろく', kun: 'と(る)', word: '記録（きろく）',
    emoji: '⛓️', doodle: '🔧⛓️🪨', gradient: 'from-amber-500 to-orange-600',
    radicals: [ { part: '金', name: 'metal', icon: '🔧' }, { part: '录', name: 'carving / lines', icon: '🪨' } ],
    story: 'A worker uses metal tools to carve lines into stone. The lines stay forever, so this is a record.',
    storyFr: 'Un ouvrier utilise des outils en métal pour graver des lignes dans la pierre. Ces lignes restent pour toujours, c\'est donc un enregistrement.',
    example: 'このビデオは会議の記録として残された。',
    exampleGlossary: [ g('ビデオ','びでお','video'), g('会議','かいぎ','meeting'), g('記録','きろく','record'), g('残された','のこされた','was left / kept') ],
  },
  { char: '延', meaning: 'prolong / extend', meaningFr: 'prolonger', on: 'えん', kun: 'の(ばす), の(べる)', word: '延期（えんき）',
    emoji: '🐍', doodle: '📅🦵➡️', gradient: 'from-teal-500 to-cyan-600',
    radicals: [ { part: '廴', name: 'long stride', icon: '🦵' }, { part: '正', name: 'straight', icon: '📏' } ],
    story: 'A long step keeps moving straight forward. It pushes the date farther away. That is to extend or postpone.',
    storyFr: 'Un grand pas continue tout droit. Il repousse la date plus loin. C\'est prolonger ou reporter.',
    example: '大雨のため、試合は延期になった。',
    exampleGlossary: [ g('大雨','おおあめ','heavy rain'), g('ため','','because of'), g('試合','しあい','game / match'), g('延期','えんき','postponement') ],
  },
  { char: '務', meaning: 'duty / task / serve', meaningFr: 'devoir / tâche', on: 'む, ぶ', kun: 'つと(める)', word: '責任者を務める（せきにんしゃをつとめる）',
    emoji: '⚔️', doodle: '🔱🛡️💼', gradient: 'from-indigo-500 to-violet-600',
    radicals: [ { part: '矛', name: 'halberd', icon: '🔱' }, { part: '力', name: 'power / effort', icon: '💪' } ],
    story: 'A guard holds a weapon with all his power. He must do his duty and protect the task he was given.',
    storyFr: 'Un garde tient une arme avec toute sa force. Il doit faire son devoir et protéger la tâche qui lui a été confiée.',
    example: '彼はプロジェクトの責任者を務めている。',
    exampleGlossary: [ g('彼','かれ','he'), g('プロジェクト','ぷろじぇくと','project'), g('責任者','せきにんしゃ','person in charge'), g('務めている','つとめている','is serving as') ],
  },
  { char: '責', meaning: 'blame / responsibility', meaningFr: 'responsabilité / blâme', on: 'せき', kun: 'せ(める)', word: '責任（せきにん）',
    emoji: '📌', doodle: '🌵💰📌', gradient: 'from-rose-500 to-pink-600',
    radicals: [ { part: '朿', name: 'thorn', icon: '🌵' }, { part: '貝', name: 'shell / value', icon: '💰' } ],
    story: 'A sharp thorn sticks into something valuable. When value is hurt, someone has to take responsibility.',
    storyFr: 'Une épine pointue pique dans quelque chose de valeur. Quand la valeur est blessée, quelqu\'un doit prendre la responsabilité.',
    example: '事故の責任は誰にあるのか。',
    exampleGlossary: [ g('事故','じこ','accident'), g('責任','せきにん','responsibility'), g('誰','だれ','who'), g('ある','','is') ],
  },
  { char: '紛', meaning: 'distract / confuse / be mixed up', meaningFr: 'confondre / perdre', on: 'ふん', kun: 'まぎ(れる), まぎ(らす)', word: '紛失（ふんしつ）',
    emoji: '🧶', doodle: '🧵✂️🌀', gradient: 'from-fuchsia-500 to-purple-600',
    radicals: [ { part: '糸', name: 'thread', icon: '🧵' }, { part: '分', name: 'part / divide', icon: '✂️' } ],
    story: 'Threads are cut into many parts and tangled together. Your mind gets confused and loses track.',
    storyFr: 'Des fils sont coupés en plusieurs morceaux et emmêlés. L\'esprit se confond et perd le fil.',
    example: '大事な書類を紛失してしまった。',
    exampleGlossary: [ g('大事','だいじ','important'), g('書類','しょるい','documents'), g('紛失','ふんしつ','losing / misplacing') ],
  },
  { char: '失', meaning: 'lose / miss', meaningFr: 'perdre', on: 'しつ', kun: 'うしな(う), お(とす)', word: '失う（うしなう）',
    emoji: '⬆️', doodle: '🚶🪨😵', gradient: 'from-slate-500 to-slate-600',
    radicals: [ { part: '大', name: 'big / person', icon: '🚶' }, { part: '一', name: 'one / obstacle', icon: '🪵' } ],
    story: 'A big person trips over one small obstacle. He drops something and loses it.',
    storyFr: 'Une grande personne trébuche sur un petit obstacle. Il lâche quelque chose et le perd.',
    example: '彼は自信を失っていた。',
    exampleGlossary: [ g('彼','かれ','he'), g('自信','じしん','self-confidence'), g('失っていた','うしなっていた','had lost') ],
  },
  { char: '決', meaning: 'decide / settle', meaningFr: 'décider / résoudre', on: 'けつ', kun: 'き(める)', word: '解決（かいけつ）',
    emoji: '💧', doodle: '💧✂️🔓', gradient: 'from-blue-500 to-indigo-600',
    radicals: [ { part: '氵', name: 'water', icon: '💦' }, { part: '夬', name: 'decide / divide', icon: '✂️' } ],
    story: 'A stream of water cuts straight through the ground. The cut is final and clear, like a decision.',
    storyFr: 'Un ruisseau d\'eau coupe droit à travers le sol. La coupure est finale et claire, comme une décision.',
    example: 'この問題を今日中に解決したい。',
    exampleGlossary: [ g('問題','もんだい','problem'), g('今日中','きょうじゅう','today / by the end of today'), g('解決','かいけつ','solution / settling') ],
  },
  { char: '計', meaning: 'measure / plan', meaningFr: 'calculer / planifier', on: 'けい', kun: 'はか(る)', word: '計画（けいかく）',
    emoji: '📐', doodle: '🗣️🔟🗺️', gradient: 'from-emerald-500 to-green-600',
    radicals: [ { part: '言', name: 'speech', icon: '💬' }, { part: '十', name: 'ten / complete', icon: '🔟' } ],
    story: 'Say each step out loud and count to ten. That is how you measure and plan carefully.',
    storyFr: 'Dites chaque étape à voix haute et comptez jusqu\'à dix. C\'est ainsi que vous mesurez et planifiez soigneusement.',
    example: '来月の旅行計画を立てる。',
    exampleGlossary: [ g('来月','らいげつ','next month'), g('旅行','りょこう','travel'), g('計画','けいかく','plan'), g('立てる','たてる','to make / set up') ],
  },
  { char: '確', meaning: 'certain / solid', meaningFr: 'certain / solide', on: 'かく', kun: 'たし(か)', word: '確認（かくにん）',
    emoji: '🪨', doodle: '🦅🪨✅', gradient: 'from-stone-500 to-zinc-600',
    radicals: [ { part: '石', name: 'stone', icon: '🗿' }, { part: '隺', name: 'high bird', icon: '🦅' } ],
    story: 'A high bird lands on a solid stone. It is safe and will not fall. That is certain.',
    storyFr: 'Un oiseau haut perché atterrit sur une pierre solide. Il est en sécurité et ne tombera pas. C\'est certain.',
    example: '予約をもう一度確認してください。',
    exampleGlossary: [ g('予約','よやく','reservation'), g('もう一度','もういちど','once more'), g('確認','かくにん','confirmation'), g('してください','','please do') ],
  },
]

// ------------------------------------------------------------------
// GRAMMAR LESSONS
// ------------------------------------------------------------------
export const grammarLessons = [
  { pattern: '〜わけがない', form: 'V-plain / i-adj / na-adj+な / N+の + わけがない', meaning: 'There is no way ~ / It is impossible that ~', meaningFr: 'Il est impossible que ~',
    image: '🙅', doodle: '🚪�❌', gradient: 'from-rose-500 to-pink-600',
    scene: 'A locked gate has a big "NO WAY" sign. The speaker says the idea is completely impossible.',
    sceneFr: 'Une porte verrouillée avec un grand panneau "PAS MOYEN". L\'orateur dit que l\'idée est totalement impossible.',
    nuance: 'Strong denial based on logic or the speaker’s judgment.',
    example: 'こんな難しい問題、私に分かるわけがない。',
    exampleGlossary: [ g('難しい','むずかしい','difficult'), g('問題','もんだい','problem'), g('私','わたし','I'), g('分かる','わかる','to understand'), g('わけがない','','there is no way') ],
  },
  { pattern: '〜わけではない', form: 'V-plain / i-adj / na-adj+な / N+の + わけではない', meaning: 'It is not (necessarily) the case that ~', meaningFr: 'Ce n\'est pas (forcément) le cas que ~',
    image: '⚖️', doodle: '⚖️↔️', gradient: 'from-amber-500 to-orange-600',
    scene: 'A scale tilts just a little. Things are not 100% one way or the other.',
    sceneFr: 'Une balance penche un peu. Les choses ne sont pas 100% d\'un côté ou de l\'autre.',
    nuance: 'Softens a statement; denies a generalization. Often paired with からといって.',
    example: '安いからといって、品質が悪いわけではない。',
    exampleGlossary: [ g('安い','やすい','cheap'), g('からといって','','just because'), g('品質','ひんしつ','quality'), g('悪い','わるい','bad'), g('わけではない','','not necessarily') ],
  },
  { pattern: '〜わけにはいかない', form: 'V-dictionary + わけにはいかない', meaning: 'Cannot ~ (because of social pressure, obligation, or the speaker\'s own will)', meaningFr: 'Je ne peux pas ~ (par devoir / obligation)',
    image: '🚫', doodle: '🚧🛣️🙅', gradient: 'from-violet-500 to-purple-600',
    scene: 'A person stands at a crossroad. A sign says "MUST NOT TURN BACK". Duty stops him.',
    sceneFr: 'Une personne se tient à un carrefour. Un panneau dit "NE PAS FAIRE DEMI-TOUR". Le devoir l\'arrête.',
    nuance: 'Emotional or moral impossibility. Stronger than 〜ことができない.',
    example: '自分が責任者なので、途中で投げ出すわけにはいかない。',
    exampleGlossary: [ g('自分','じぶん','oneself'), g('責任者','せきにんしゃ','person in charge'), g('途中','とちゅう','halfway'), g('投げ出す','なげだす','to abandon'), g('わけにはいかない','','cannot (because of duty)') ],
  },
  { pattern: '〜ざるを得ない', form: 'V-ない-stem + ざるを得ない', meaning: 'Have no choice but to ~', meaningFr: 'Je n\'ai pas d\'autre choix que de ~',
    image: '⛓️', doodle: '⛓️🚪➡️', gradient: 'from-cyan-500 to-blue-600',
    scene: 'A person\'s hands are tied. Circumstances force them through the only open door.',
    sceneFr: 'Les mains d\'une personne sont liées. Les circonstances la forcent à passer par la seule porte ouverte.',
    nuance: 'External pressure leaves no other option. Often used in formal or written Japanese.',
    example: '書類を紛失したため、最初から作り直さざるを得ない。',
    exampleGlossary: [ g('書類','しょるい','documents'), g('紛失','ふんしつ','losing'), g('最初','さいしょ','from the beginning'), g('作り直す','つくりなおす','to remake'), g('ざるを得ない','','have no choice but') ],
  },
  { pattern: '〜かねる', form: 'V-masu-stem + かねる', meaning: 'Be unable / hesitate to ~', meaningFr: 'Je ne peux pas / j\'hésite à ~',
    image: '⏸️', doodle: '🚪⏸️🤚', gradient: 'from-sky-500 to-indigo-600',
    scene: 'A person puts a hand on the door handle but pauses. They cannot open it, politely.',
    sceneFr: 'Une personne pose la main sur la poignée mais s\'arrête. Elle ne peut pas ouvrir, poliment.',
    nuance: 'Polite refusal. Cannot do something due to ability, permission, or tact.',
    example: 'その件については、こちらではお答えしかねます。',
    exampleGlossary: [ g('件','けん','matter'), g('こちら','','we / here'), g('答え','こたえ','answer'), g('かねる','','be unable / hesitate to do') ],
  },
  { pattern: '〜かねない', form: 'V-masu-stem + かねない', meaning: 'There is a possibility that ~ (usually bad)', meaningFr: 'Il se pourrait que ~ (souvent négatif)',
    image: '⚠️', doodle: '⚠️⛅', gradient: 'from-red-500 to-rose-600',
    scene: 'A warning triangle flashes on the horizon. Something bad might happen.',
    sceneFr: 'Un triangle d\'avertissement clignote à l\'horizon. Quelque chose de mauvais pourrait arriver.',
    nuance: 'Speaker is worried that something undesirable may occur.',
    example: 'このままだと、計画が延期になりかねない。',
    exampleGlossary: [ g('このまま','','like this'), g('計画','けいかく','plan'), g('延期','えんき','postponement'), g('かねない','','there is a possibility that') ],
  },
  { pattern: '〜べきだ / 〜べきではない', form: 'V-dictionary + べきだ / べきではない', meaning: 'Should / should not ~', meaningFr: 'Je devrais / je ne devrais pas ~',
    image: '🧭', doodle: '🧭➡️✅', gradient: 'from-emerald-500 to-teal-600',
    scene: 'A compass points clearly in the right direction. You should follow it, or avoid the wrong way.',
    sceneFr: 'Une boussole pointe clairement dans la bonne direction. Vous devriez la suivre, ou éviter le mauvais chemin.',
    nuance: 'Strong advice or social duty. The negative is a warning.',
    example: '時間がないからといって、仕事を雑にするべきではない。',
    exampleGlossary: [ g('時間','じかん','time'), g('からといって','','just because'), g('仕事','しごと','work'), g('雑に','ぞうに','carelessly'), g('べきではない','','should not') ],
  },
  { pattern: '〜ものの', form: 'V-plain / i-adj / na-adj+な / N+の + ものの', meaning: 'Although ~ (contrast)', meaningFr: 'Bien que ~ (contraste)',
    image: '🏔️', doodle: '🏔️👆⬇️', gradient: 'from-lime-500 to-green-600',
    scene: 'A climber reaches the top, but the way down is still there. Success and contrast together.',
    sceneFr: 'Un grimpeur atteint le sommet, mais la descente est toujours là. Succès et contraste ensemble.',
    nuance: 'Acknowledges a fact, then points out an opposing result.',
    example: '計画は立てたものの、実行できなかった。',
    exampleGlossary: [ g('計画','けいかく','plan'), g('立てる','たてる','to make'), g('実行','じっこう','execution'), g('できなかった','','could not'), g('ものの','','although') ],
  },
  { pattern: '〜からといって', form: 'V-plain / i-adj / na-adj+な / N+だ + からといって', meaning: 'Just because ~ (doesn\'t mean)', meaningFr: 'Ce n\'est pas parce que ~ que ~',
    image: '🔁', doodle: '🀄🚫📉', gradient: 'from-yellow-500 to-amber-600',
    scene: 'One domino falls, but the others refuse to follow. One cause does not guarantee the result.',
    sceneFr: 'Un domino tombe, mais les autres refusent de suivre. Une cause ne garantit pas le résultat.',
    nuance: 'Denies an expected conclusion; often followed by わけではない.',
    example: '日本人だからといって、日本語が上手だとは限らない。',
    exampleGlossary: [ g('日本人','にほんじん','Japanese person'), g('からといって','','just because'), g('日本語','にほんご','Japanese language'), g('上手','じょうず','skilled'), g('とは限らない','','not necessarily') ],
  },
  { pattern: '〜にしては', form: 'V-plain / i-adj / na-adj+な / N + にしては', meaning: 'Considering ~ / For ~', meaningFr: 'Vu que ~ / Pour ~',
    image: '📊', doodle: '🏋️‍♂️👀', gradient: 'from-fuchsia-500 to-pink-600',
    scene: 'A small athlete lifts heavy weights. For his level, it is surprisingly good.',
    sceneFr: 'Un petit athlète soulève des poids lourds. Pour son niveau, c\'est étonnamment bon.',
    nuance: 'Expresses surprise or evaluation relative to a standard.',
    example: '初心者にしては、とても上手だ。',
    exampleGlossary: [ g('初心者','しんしゃ','beginner'), g('にしては','','considering / for'), g('とても','','very'), g('上手','じょうず','skilled') ],
  },
  { pattern: '〜ないことはない', form: 'V-ない + ことはない', meaning: 'It is not that one cannot ~ / It is possible to ~', meaningFr: 'Ce n\'est pas impossible de ~',
    image: '🌉', doodle: '🌫️🌉', gradient: 'from-blue-500 to-sky-600',
    scene: 'A bridge appears in the fog. It is faint, but a way still exists.',
    sceneFr: 'Un pont apparaît dans le brouillard. Il est faible, mais un chemin existe encore.',
    nuance: 'Double negative; leaves room for possibility without promising it.',
    example: '話せば、何とか解決しないこともない。',
    exampleGlossary: [ g('話せば','はなせば','if we talk'), g('何とか','なんとか','somehow'), g('解決','かいけつ','solution'), g('ないこともない','','it is not impossible') ],
  },
  { pattern: '〜どころではない', form: 'V-dictionary / N + どころではない', meaning: 'This is not the time/place for ~ / Far from ~', meaningFr: 'Ce n\'est pas le moment pour ~',
    image: '⏰', doodle: '⏰🔥🚫', gradient: 'from-orange-500 to-red-600',
    scene: 'A clock rings while the room is on fire. This is not the moment to think about small things.',
    sceneFr: 'Une horloge sonne pendant que la pièce est en feu. Ce n\'est pas le moment de penser à de petites choses.',
    nuance: 'Shows the situation is too serious to consider the stated thing.',
    example: '今は遊んでいるどころではない。',
    exampleGlossary: [ g('今','いま','now'), g('遊んでいる','あそんでいる','playing'), g('どころではない','','not the time/place for') ],
  },
]

// ------------------------------------------------------------------
// VOCABULARY LESSONS
// ------------------------------------------------------------------
export const vocabLessons = [
  { word: '終日', reading: 'しゅうじつ', meaning: 'all day long', meaningFr: 'toute la journée', image: '🌞', doodle: '🌅☀️🌇', gradient: 'from-yellow-400 to-orange-500',
    story: 'The sun goes from morning to evening. The whole day is covered, from start to finish.',
    storyFr: 'Le soleil va du matin au soir. Toute la journée est couverte, du début à la fin.',
    collocation: '終日営業（しゅうじつえいぎょう）',
    example: 'この店は終日営業している。',
    exampleGlossary: [ g('店','みせ','shop'), g('終日','しゅうじつ','all day long'), g('営業','えいぎょう','business operation'), g('している','','is doing') ],
  },
  { word: '延期', reading: 'えんき', meaning: 'postponement', meaningFr: 'report / ajournement', image: '🗓️', doodle: '📅➡️📅', gradient: 'from-teal-400 to-cyan-500',
    story: 'A calendar is stretched forward. The event moves to a later day.',
    storyFr: 'Un calendrier est étiré vers l\'avant. L\'événement est déplacé à un jour plus tard.',
    collocation: '試合が延期になる',
    example: '雨で試合が延期になった。',
    exampleGlossary: [ g('雨','あめ','rain'), g('試合','しあい','game / match'), g('延期','えんき','postponement'), g('なった','','became') ],
  },
  { word: '集中', reading: 'しゅうちゅう', meaning: 'concentration', meaningFr: 'concentration', image: '🎯', doodle: '👁️🎯🎯', gradient: 'from-red-400 to-rose-500',
    story: 'All arrows fly to the center of the target. Nothing else gets attention.',
    storyFr: 'Toutes les flèches volent au centre de la cible. Rien d\'autre n\'attire l\'attention.',
    collocation: '集中力を高める',
    example: '集中して勉強する必要がある。',
    exampleGlossary: [ g('集中','しゅうちゅう','concentration'), g('勉強','べんきょう','study'), g('必要','ひつよう','need'), g('ある','','is') ],
  },
  { word: '解決', reading: 'かいけつ', meaning: 'solution / settlement', meaningFr: 'solution / règlement', image: '✅', doodle: '💧❓➡️✅', gradient: 'from-blue-400 to-indigo-500',
    story: 'Water cuts through the knot. The problem opens up like a lock being opened.',
    storyFr: 'L\'eau coupe le nœud. Le problème s\'ouvre comme un cadenas qu\'on déverrouille.',
    collocation: '問題を解決する',
    example: 'トラブルを早く解決したい。',
    exampleGlossary: [ g('トラブル','','trouble'), g('早く','はやく','quickly'), g('解決','かいけつ','solution / settlement'), g('したい','','want to do') ],
  },
  { word: '計画', reading: 'けいかく', meaning: 'plan', meaningFr: 'plan', image: '🗺️', doodle: '🗣️🔟🗺️', gradient: 'from-emerald-400 to-green-500',
    story: 'A map is drawn step by step, counting each part. That is a careful plan.',
    storyFr: 'Une carte est dessinée étape par étape, en comptant chaque partie. C\'est un plan soigneux.',
    collocation: '計画を立てる',
    example: '来月の旅行計画を立てる。',
    exampleGlossary: [ g('来月','らいげつ','next month'), g('旅行','りょこう','travel'), g('計画','けいかく','plan'), g('立てる','たてる','to make') ],
  },
  { word: '確認', reading: 'かくにん', meaning: 'confirmation', meaningFr: 'confirmation', image: '🔍', doodle: '🧐🪨✅', gradient: 'from-stone-400 to-zinc-500',
    story: 'A bird checks the solid stone before it lands. It wants to be sure.',
    storyFr: 'Un oiseau vérifie la pierre solide avant d\'atterrir. Il veut être sûr.',
    collocation: '予約を確認する',
    example: 'もう一度予約を確認してください。',
    exampleGlossary: [ g('もう一度','もういちど','once more'), g('予約','よやく','reservation'), g('確認','かくにん','confirmation'), g('してください','','please do') ],
  },
  { word: '責任', reading: 'せきにん', meaning: 'responsibility', meaningFr: 'responsabilité', image: '⚖️', doodle: '🌵💰⚖️', gradient: 'from-rose-400 to-pink-500',
    story: 'When something valuable is hurt, the balance must be held. Someone must take responsibility.',
    storyFr: 'Quand quelque chose de valeur est blessé, la balance doit être tenue. Quelqu\'un doit prendre la responsabilité.',
    collocation: '責任を負う',
    example: '彼は事故の責任を負った。',
    exampleGlossary: [ g('彼','かれ','he'), g('事故','じこ','accident'), g('責任','せきにん','responsibility'), g('負った','おった','took / bore') ],
  },
  { word: '全体', reading: 'ぜんたい', meaning: 'whole / entire', meaningFr: 'ensemble / totalité', image: '🌐', doodle: '🧩🧩🧩➡️🌐', gradient: 'from-sky-400 to-blue-500',
    story: 'All small parts come together to make one complete globe.',
    storyFr: 'Toutes les petites parties se rassemblent pour former un globe complet.',
    collocation: '全体像を把握する',
    example: '全体像を把握するのに時間がかかった。',
    exampleGlossary: [ g('全体像','ぜんたいぞう','whole picture'), g('把握','はあく','grasp / understand'), g('時間','じかん','time'), g('かかった','','took') ],
  },
  { word: '無理', reading: 'むり', meaning: 'impossible / unreasonable', meaningFr: 'impossible / déraisonnable', image: '🧱', doodle: '🧱🚶🚫', gradient: 'from-slate-400 to-slate-500',
    story: 'A wall blocks the road. Going through it is impossible.',
    storyFr: 'Un mur bloque le chemin. Passer à travers est impossible.',
    collocation: '無理をしない',
    example: '無理をしないで、休んでください。',
    exampleGlossary: [ g('無理','むり','impossible / overdoing it'), g('しないで','','without doing'), g('休んで','やすんで','rest'), g('ください','','please') ],
  },
  { word: '傾向', reading: 'けいこう', meaning: 'tendency / trend', meaningFr: 'tendance / orientation', image: '📈', doodle: '📉↗️📈', gradient: 'from-violet-400 to-purple-500',
    story: 'A graph slowly tilts to one side. It shows the direction things are moving.',
    storyFr: 'Un graphique penche lentement d\'un côté. Il montre la direction dans laquelle les choses vont.',
    collocation: '〜する傾向がある',
    example: '若者はスマホを使う傾向がある。',
    exampleGlossary: [ g('若者','わかもの','young people'), g('スマホ','','smartphone'), g('使う','つかう','to use'), g('傾向','けいこう','tendency') ],
  },
]

// ------------------------------------------------------------------
// READING PASSAGES
// ------------------------------------------------------------------
export const passages = [
  {
    title: 'テレワークの新しい形',
    level: 'N2',
    time: 5,
    text: '近年、多くの企業はテレワーク制度を導入している。しかし、一部の社員は家での集中力が続かないと感じている。企業側としては、オフィスを自由に使える「ハイブリッド勤務」を新たな選択肢として提示する動きが見られる。導入に当たって、コストや社員の意思を尊重することが重要だと専門家は指摘している。',
    glossary: [
      { word: '企業', reading: 'きぎょう', meaning: 'company / enterprise', image: '🏢', mnemonic: 'A big building full of businesses.' },
      { word: '導入', reading: 'どうにゅう', meaning: 'introduction / adoption', image: '📥', mnemonic: 'Carry something in and start using it.' },
      { word: '集中力', reading: 'しゅうちゅうりょく', meaning: 'concentration', image: '🎯', mnemonic: 'Power focused on the target.' },
      { word: '選択肢', reading: 'せんたくし', meaning: 'option / choice', image: '🍽️', mnemonic: 'A menu of choices on a plate.' },
      { word: '尊重', reading: 'そんちょう', meaning: 'respect / esteem', image: '🤝', mnemonic: 'Hold someone\'s opinion with weight.' },
      { word: '専門家', reading: 'せんもんか', meaning: 'expert / specialist', image: '👨‍🔬', mnemonic: 'A person with a specialized magnifying glass.' },
    ],
    questions: [
      { prompt: 'この文章で筆者が最も言いたいことは何か。', options: [
        { label: 'テレワークは全員に合う制度である', correct: false },
        { label: 'ハイブリッド勤務が新しい選択肢として考えられている', correct: true },
        { label: '社員はオフィスでしか働けない', correct: false },
        { label: '専門家はテレワークに反対している', correct: false } ],
        explanation: 'The passage states that companies are presenting “ハイブリッド勤務” as a new option, while noting the need to respect employee opinions and costs.' },
      { prompt: '「尊重することが重要」とあるが、何を尊重する必要があるか。', options: [
        { label: '社員の意思', correct: true },
        { label: '競合企業の意見', correct: false },
        { label: '海外の法律', correct: false },
        { label: '経済成長だけ', correct: false } ],
        explanation: 'The sentence says “コストや社員の意思を尊重することが重要だ” — cost and employee will.' },
    ],
  },
  {
    title: '気候変動とエネルギー政策',
    level: 'N2',
    time: 6,
    text: '世界中で気候変動への関心が高まる一方、エネルギー政策の見直しが急がれている。専門家は、再生可能エネルギーの比率を高めることは避けられない課題だと指摘している。とりわけ、若者世代には持続可能な社会への理解が求められる。しかし、技術的な課題やコストの問題が残されているのも事実だ。',
    glossary: [
      { word: '気候変動', reading: 'きこうへんどう', meaning: 'climate change', image: '🌍', mnemonic: 'The globe shifting its weather patterns.' },
      { word: '見直し', reading: 'みなおし', meaning: 'review / reconsideration', image: '👀', mnemonic: 'Look again to re-evaluate.' },
      { word: '再生可能', reading: 'さいせいかのう', meaning: 'renewable', image: '🌱', mnemonic: 'New life growing back again and again.' },
      { word: '比率', reading: 'ひりつ', meaning: 'ratio', image: '⚖️', mnemonic: 'The balance of how much of each part.' },
      { word: '持続可能', reading: 'じぞくかのう', meaning: 'sustainable', image: '♻️', mnemonic: 'A cycle that can keep going forever.' },
      { word: '残る', reading: 'のこる', meaning: 'to remain', image: '🧩', mnemonic: 'A puzzle piece still left on the table.' },
    ],
    questions: [
      { prompt: '専門家はどのような課題を避けられないと考えているか。', options: [
        { label: '再生可能エネルギーの比率を高めること', correct: true },
        { label: '化石燃料を増やすこと', correct: false },
        { label: '若者を教育から外すこと', correct: false },
        { label: 'コストを無視すること', correct: false } ],
        explanation: 'The experts say “再生可能エネルギーの比率を高めることは避けられない課題だ”.' },
      { prompt: '筆者が「技術的な課題やコストの問題が残されている」と述べているのはどういう目的か。', options: [
        { label: '問題が解決したことを示す', correct: false },
        { label: '解決すべき課題があることを示す', correct: true },
        { label: '若者の責任を強調する', correct: false },
        { label: '専門家の意見を否定する', correct: false } ],
        explanation: 'Listing remaining issues shows there is still work to do, adding nuance to the main argument.' },
    ],
  },
  {
    title: 'スマホと情報リテラシー',
    level: 'N2',
    time: 5,
    text: 'スマートフォンの普及により、人々はいつでも情報にアクセスできるようになった。一方で、誤った情報が瞬く間に広がるリスクも増している。ユーザー一人ひとりが情報の出所を確認する意識を持つことが、信頼できる社会を作るうえで不可欠である。',
    glossary: [
      { word: '普及', reading: 'ふきゅう', meaning: 'spread / diffusion', image: '📡', mnemonic: 'Waves spreading everywhere like Wi-Fi.' },
      { word: 'アクセス', reading: 'あくせす', meaning: 'access', image: '🔑', mnemonic: 'A key opening the door to information.' },
      { word: '誤った', reading: 'あやまった', meaning: 'mistaken / false', image: '❌', mnemonic: 'A big red X marking the wrong answer.' },
      { word: '瞬く間', reading: 'またたくま', meaning: 'in a flash / instantly', image: '⚡', mnemonic: 'A lightning flash in a split second.' },
      { word: '出所', reading: 'しゅっしょ', meaning: 'source / origin', image: '📍', mnemonic: 'A pin marking where something comes from.' },
      { word: '不可欠', reading: 'ふかけつ', meaning: 'indispensable', image: '🔒', mnemonic: 'An essential piece that cannot be missing.' },
    ],
    questions: [
      { prompt: '筆者が最も強調していることは何か。', options: [
        { label: 'スマホを使わないこと', correct: false },
        { label: '情報の出所を確認する意識の重要性', correct: true },
        { label: '誤った情報を作ること', correct: false },
        { label: '社会を信頼できなくする方法', correct: false } ],
        explanation: 'The final sentence stresses that each user verifying the source is indispensable for a trustworthy society.' },
      { prompt: '「一方で」の前後で何が対比されているか。', options: [
        { label: '便利な点と危険な点', correct: true },
        { label: 'スマホの値段と性能', correct: false },
        { label: '若者と高齢者', correct: false },
        { label: '国内と海外', correct: false } ],
        explanation: '前: easy access; 後: risk of false information spreading fast. It is convenience vs risk.' },
    ],
  },
]

// ------------------------------------------------------------------
// DRILL BANK
// ------------------------------------------------------------------
export const questions = [
  { id: 1, type: 'Vocabulary', format: 'meaning', prompt: 'この道路は、集中工事のため終日通行止めとなります。', target: '終日', options: [
    { label: '週末', correct: false }, { label: '夜間', correct: false }, { label: '一日中', correct: true }, { label: '今日まで', correct: false } ],
    explanation: '終日（しゅうじつ）= “all day long.” 一日中 is the closest match.', hint: 'Think of the sun (日) from start to finish.' },
  { id: 2, type: 'Vocabulary', format: 'reading', prompt: 'このままトラブルの解決が長引くと、全体の計画が延期になりかねない。', target: '延期', options: [
    { label: 'えんぎ', correct: false }, { label: 'えんき', correct: true }, { label: 'けんき', correct: false }, { label: 'てんき', correct: false } ],
    explanation: '延期 is read えんき (postponement).', hint: '延 stretches “en”; 期 is “time/ki”.' },
  { id: 3, type: 'Grammar', format: 'structure', prompt: '大事なプロジェクトの提出用書類を紛失してしまったため、最初からすべて作り直さ＿＿＿。', target: null, options: [
    { label: 'わけにはいかない', correct: false }, { label: 'ざるを得ない', correct: true }, { label: 'かねない', correct: false }, { label: 'がちだ', correct: false } ],
    explanation: '作り直さざるを得ない = “have no choice but to redo.” ざるを得ない attaches to the ない-stem.', hint: 'Forced by circumstances — tied hands.' },
  { id: 4, type: 'Grammar', format: 'structure', prompt: '自分が責任者を務めている仕事なのだから、途中で投げ出す＿＿＿。', target: null, options: [
    { label: 'わけにはいかない', correct: true }, { label: 'わけがない', correct: false }, { label: 'どころではない', correct: false }, { label: 'かねない', correct: false } ],
    explanation: '投げ出すわけにはいかない = “cannot abandon (because of responsibility).” わけにはいかない uses the dictionary form.', hint: 'Moral / duty-based impossibility.' },
  { id: 5, type: 'Vocabulary', format: 'meaning', prompt: '彼の意見には一理あるが、全体像を考えると無理がある。', target: '一理', options: [
    { label: '完全な道理', correct: false }, { label: '一部の真理', correct: true }, { label: '一つの理由', correct: false }, { label: '一点の欠点', correct: false } ],
    explanation: '一理（いちり）= “some truth (in an argument).” 一部の真理 is closest.', hint: 'One ray of light, not the whole sun.' },
  { id: 6, type: 'Grammar', format: 'structure', prompt: '時間がないからといって、仕事を雑にする＿＿＿。', target: null, options: [
    { label: 'べきではない', correct: true }, { label: 'わけがない', correct: false }, { label: 'きらいがある', correct: false }, { label: 'に越したことはない', correct: false } ],
    explanation: '〜べきではない = “should not do.” It fits the warning not to be careless.', hint: 'Compass pointing the wrong way — avoid this.' },
  { id: 7, type: 'Grammar', format: 'structure', prompt: '初心者＿＿＿、とても上手だ。', target: null, options: [
    { label: 'にしては', correct: true }, { label: 'からこそ', correct: false }, { label: 'ばかりか', correct: false }, { label: 'だけに', correct: false } ],
    explanation: 'にしては = “considering/ for a ~”. Expresses surprise relative to a standard.', hint: 'The small athlete lifting heavy weights.' },
  { id: 8, type: 'Vocabulary', format: 'reading', prompt: 'その問題を話し合って、最後には解決できた。', target: '解決', options: [
    { label: 'かいけつ', correct: true }, { label: 'がいけつ', correct: false }, { label: 'かいこつ', correct: false }, { label: 'かいけち', correct: false } ],
    explanation: '解決 is read かいけつ (settlement / resolution).', hint: 'Water cuts through the problem.' },
  { id: 9, type: 'Grammar', format: 'structure', prompt: '安い＿＿＿、品質が悪いわけではない。', target: null, options: [
    { label: 'からこそ', correct: false }, { label: 'からといって', correct: true }, { label: 'だけに', correct: false }, { label: 'ものの', correct: false } ],
    explanation: 'からといって = “just because.” One cause does not guarantee the conclusion.', hint: 'A single domino does not knock over the whole row.' },
  { id: 10, type: 'Grammar', format: 'structure', prompt: '今は遊んでいる＿＿＿。試験が近い。', target: null, options: [
    { label: 'わけではない', correct: false }, { label: 'どころではない', correct: true }, { label: 'わけがない', correct: false }, { label: 'べきではない', correct: false } ],
    explanation: 'どころではない = “this is not the time/place for ~.”', hint: 'Clock ringing during a fire — not now.' },
  { id: 11, type: 'Vocabulary', format: 'meaning', prompt: '近年、スマホの利用が増え続けている。', target: '近年', options: [
    { label: '先月', correct: false }, { label: '最近の数年', correct: true }, { label: '今年だけ', correct: false }, { label: '毎年', correct: false } ],
    explanation: '近年（きんねん）= “recent years.”', hint: 'The years close to now.' },
  { id: 12, type: 'Vocabulary', format: 'reading', prompt: '再生可能エネルギーの利用を広げる必要がある。', target: '再生可能', options: [
    { label: 'さいせいかのう', correct: true }, { label: 'させいかのう', correct: false }, { label: 'さいしょうかのう', correct: false }, { label: 'さいせいかの', correct: false } ],
    explanation: '再生可能 is read さいせいかのう (renewable).', hint: '生 means life/sei, 可能 means possible.' },
  { id: 13, type: 'Vocabulary', format: 'meaning', prompt: '睡眠は健康に不可欠だ。', target: '不可欠', options: [
    { label: '避けられる', correct: false }, { label: '必須の', correct: true }, { label: '危険な', correct: false }, { label: '簡単な', correct: false } ],
    explanation: '不可欠（ふかけつ）= “indispensable / essential.”', hint: 'Cannot be missing from the puzzle.' },
  { id: 14, type: 'Vocabulary', format: 'reading', prompt: 'このサイトは信頼できる出所からの情報を載せている。', target: '出所', options: [
    { label: 'でしょ', correct: false }, { label: 'しゅっしょ', correct: true }, { label: 'でしゅう', correct: false }, { label: 'しゅうしょ', correct: false } ],
    explanation: '出所 is read しゅっしょ (source / origin).', hint: '出 = go out (shutsu), 所 = place (sho).' },
  { id: 15, type: 'Vocabulary', format: 'meaning', prompt: '無理をすると体を壊す。', target: '無理', options: [
    { label: '努力', correct: false }, { label: '無理なこと / 無茶', correct: true }, { label: '休息', correct: false }, { label: '楽なこと', correct: false } ],
    explanation: '無理（むり）= “impossible / overdoing it.”', hint: 'A wall you cannot push through.' },
  { id: 16, type: 'Grammar', format: 'structure', prompt: 'こんなに安いのだから、本物＿＿＿。', target: null, options: [
    { label: 'わけがない', correct: true }, { label: 'わけではない', correct: false }, { label: 'わけだ', correct: false }, { label: 'わけにはいかない', correct: false } ],
    explanation: 'わけがない = “there is no way / it is impossible.”', hint: 'A locked gate saying “no way.”' },
  { id: 17, type: 'Grammar', format: 'structure', prompt: '試験は受かったものの、点數はよくなかった。', target: null, options: [
    { label: 'からといって', correct: false }, { label: 'ものの', correct: true }, { label: 'にしては', correct: false }, { label: 'ざるを得ない', correct: false } ],
    explanation: 'ものの = “although / but.”', hint: 'Reach the top, but the descent remains.' },
  { id: 18, type: 'Grammar', format: 'structure', prompt: '一人で行けないことはないが、危険だ。', target: null, options: [
    { label: '不可能ではない', correct: true }, { label: '絶対に行ける', correct: false }, { label: '行くべきではない', correct: false }, { label: '行くわけがない', correct: false } ],
    explanation: '～ないことはない = “it is not that one cannot ~.”', hint: 'A bridge in the fog — faint but possible.' },
  { id: 19, type: 'Grammar', format: 'structure', prompt: '彼は毎日練習しているから、上手な＿＿＿。', target: null, options: [
    { label: 'はずだ', correct: true }, { label: 'わけだ', correct: false }, { label: 'べきだ', correct: false }, { label: 'ものだ', correct: false } ],
    explanation: '～はずだ = “should be / expected to be.”', hint: 'Daily practice makes a likely result.' },
  { id: 20, type: 'Grammar', format: 'structure', prompt: '海外生活が十年もある＿＿＿、日本語が少し下手だ。', target: null, options: [
    { label: 'にしては', correct: true }, { label: 'からして', correct: false }, { label: 'からといって', correct: false }, { label: 'だけに', correct: false } ],
    explanation: 'にしては = “considering / for a ~” — expresses surprise relative to a standard.', hint: 'A small athlete lifting big weights.' },
]

// ------------------------------------------------------------------
// COMMON WORDS DICTIONARY — for global double-click / lookup coverage
// ------------------------------------------------------------------
export const commonWords = [
  g('近年', 'きんねん', 'recent years'),
  g('多く', 'おおく', 'many'),
  g('企業', 'きぎょう', 'company / enterprise'),
  g('テレワーク', 'てれわーく', 'remote work'),
  g('制度', 'せいど', 'system / institution'),
  g('導入', 'どうにゅう', 'introduction / adoption'),
  g('一部', 'いちぶ', 'a part'),
  g('社員', 'しゃいん', 'employee'),
  g('家', 'いえ', 'house / home'),
  g('集中力', 'しゅうちゅうりょく', 'concentration'),
  g('続く', 'つづく', 'to continue'),
  g('感じる', 'かんじる', 'to feel'),
  g('自由', 'じゆう', 'freedom'),
  g('使える', 'つかえる', 'can use'),
  g('ハイブリッド', 'はいぶりっど', 'hybrid'),
  g('勤務', 'きんむ', 'work / service'),
  g('新たな', 'あらたな', 'new'),
  g('選択肢', 'せんたくし', 'option'),
  g('提示', 'ていじ', 'presentation / showing'),
  g('動き', 'うごき', 'movement / trend'),
  g('見られる', 'みられる', 'can be seen'),
  g('当たって', 'あたって', 'in doing / when'),
  g('コスト', 'こすと', 'cost'),
  g('意思', 'いし', 'intention'),
  g('尊重', 'そんちょう', 'respect'),
  g('重要', 'じゅうよう', 'important'),
  g('専門家', 'せんもんか', 'expert'),
  g('指摘', 'してき', 'pointing out'),
  g('世界中', 'せかいじゅう', 'around the world'),
  g('気候変動', 'きこうへんどう', 'climate change'),
  g('関心', 'かんしん', 'interest / concern'),
  g('高まる', 'たかまる', 'to rise / increase'),
  g('一方', 'いっぽう', 'on the other hand'),
  g('政策', 'せいさく', 'policy'),
  g('見直し', 'みなおし', 'review'),
  g('急がれる', 'せがれる', 'to be pressed / urgent'),
  g('再生可能', 'さいせいかのう', 'renewable'),
  g('比率', 'ひりつ', 'ratio'),
  g('高める', 'たかめる', 'to raise'),
  g('避けられない', 'さけられない', 'unavoidable'),
  g('課題', 'かだい', 'issue / task'),
  g('とりわけ', 'とりわけ', 'especially'),
  g('若者', 'わかもの', 'young people'),
  g('世代', 'せだい', 'generation'),
  g('持続可能', 'じぞくかのう', 'sustainable'),
  g('社会', 'しゃかい', 'society'),
  g('理解', 'りかい', 'understanding'),
  g('求められる', 'もとめられる', 'is required'),
  g('技術的', 'ぎじゅつてき', 'technical'),
  g('問題', 'もんだい', 'problem'),
  g('残る', 'のこる', 'to remain'),
  g('スマートフォン', 'すまーとふぉん', 'smartphone'),
  g('普及', 'ふきゅう', 'spread / diffusion'),
  g('人々', 'ひとびと', 'people'),
  g('いつでも', 'いつでも', 'anytime'),
  g('情報', 'じょうほう', 'information'),
  g('アクセス', 'あくせす', 'access'),
  g('できる', 'できる', 'can do / to be able'),
  g('一方で', 'いっぽうで', 'on the other hand'),
  g('誤った', 'あやまった', 'mistaken / false'),
  g('瞬く間', 'またたくま', 'in a flash'),
  g('広がる', 'ひろがる', 'to spread'),
  g('リスク', 'りすく', 'risk'),
  g('増す', 'ます', 'to increase'),
  g('ユーザー', 'ゆーざー', 'user'),
  g('一人ひとり', 'ひとりひとり', 'each individual'),
  g('出所', 'しゅっしょ', 'source / origin'),
  g('確認', 'かくにん', 'confirmation'),
  g('意識', 'いしき', 'awareness'),
  g('持つ', 'もつ', 'to hold / have'),
  g('信頼', 'しんらい', 'trust'),
  g('作る', 'つくる', 'to make'),
  g('上で', 'うえで', 'in order to / for'),
  g('不可欠', 'ふかけつ', 'indispensable'),
  g('原因', 'げんいん', 'cause'),
  g('結果', 'けっか', 'result'),
  g('目的', 'もくてき', 'purpose'),
  g('方法', 'ほうほう', 'method'),
  g('場合', 'ばあい', 'case / situation'),
  g('内容', 'ないよう', 'content'),
  g('意味', 'いみ', 'meaning'),
  g('文章', 'ぶんしょう', 'text / sentence'),
  g('言葉', 'ことば', 'word / language'),
  g('説明', 'せつめい', 'explanation'),
  g('知識', 'ちしき', 'knowledge'),
  g('調査', 'ちょうさ', 'survey / investigation'),
  g('考える', 'かんがえる', 'to think'),
  g('思う', 'おもう', 'to think / feel'),
  g('信じる', 'しんじる', 'to believe'),
  g('期待', 'きたい', 'expectation'),
  g('必要', 'ひつよう', 'necessity / need'),
  g('大切', 'たいせつ', 'important'),
  g('安全', 'あんぜん', 'safety'),
  g('危険', 'きけん', 'danger'),
  g('正しい', 'ただしい', 'correct'),
  g('普通', 'ふつう', 'normal'),
  g('特別', 'とくべつ', 'special'),
  g('同じ', 'おなじ', 'same'),
  g('違う', 'ちがう', 'different'),
  g('例えば', 'たとえば', 'for example'),
  g('特に', 'とくに', 'especially'),
  g('実は', 'じつは', 'actually'),
  g('最も', 'もっとも', 'most'),
  g('最後', 'さいご', 'last / end'),
  g('最初', 'さいしょ', 'first / beginning'),
  g('現在', 'げんざい', 'present'),
  g('未来', 'みらい', 'future'),
  g('過去', 'かこ', 'past'),
  g('他', 'ほか', 'other'),
  g('中', 'なか', 'inside / during'),
  g('上', 'うえ', 'top / above'),
  g('下', 'した', 'bottom / below'),
  g('外', 'そと', 'outside'),
  g('内', 'うち', 'inside'),
  g('前', 'まえ', 'before / front'),
  g('後', 'あと', 'after / behind'),
  g('人', 'ひと', 'person'),
  g('物', 'もの', 'thing'),
  g('事', 'こと', 'thing / matter'),
  g('所', 'ところ', 'place'),
  g('場所', 'ばしょ', 'place'),
  g('状態', 'じょうたい', 'condition'),
  g('程度', 'ていど', 'degree / extent'),
  g('理由', 'りゆう', 'reason'),
  g('近', 'ちか', 'near'),
  g('年', 'とし', 'year'),
  g('月', 'つき', 'moon / month'),
  g('日', 'ひ', 'day / sun'),
  g('時', 'とき', 'time / when'),
  g('大きい', 'おおきい', 'big'),
  g('小さい', 'ちいさい', 'small'),
  g('高い', 'たかい', 'tall / high'),
  g('低い', 'ひくい', 'low'),
  g('古い', 'ふるい', 'old'),
  g('新しい', 'あたらしい', 'new'),
  g('長い', 'ながい', 'long'),
  g('短い', 'みじかい', 'short'),
  g('早い', 'はやい', 'early / fast'),
  g('遅い', 'おそい', 'late / slow'),
  g('難しい', 'むずかしい', 'difficult'),
  g('易しい', 'やさしい', 'easy'),
  g('忙しい', 'いそがしい', 'busy'),
  g('楽しい', 'たのしい', 'fun'),
  g('少ない', 'すくない', 'few / little'),
  g('多い', 'おおい', 'many'),
  g('色々', 'いろいろ', 'various'),
  g('全て', 'すべて', 'all'),
  g('全部', 'ぜんぶ', 'all'),
  g('全員', 'ぜんいん', 'everyone'),
]
